name: "K3s Master"
version: "1.2.0"
slug: "k3s_master"
description: "Runs a K3s control-plane server on Home Assistant OS with persistent data"
url: "https://github.com/koenigsreiter/homeassistant-addons/tree/main/k3s-master"
arch:
  - aarch64
  - amd64
startup: services
boot: auto
host_network: true
privileged:
  - NET_ADMIN
  - SYS_ADMIN
  - CAP_SYS_MODULE
map:
  - config:rw
  - share:rw
options:
  cluster_token: "mysecret"
  data_path: "/data/k3s"
  extra_args: ""
schema:
  cluster_token: str
  data_path: str
  extra_args: str
