# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: K3s Master
version: "0.1.0"
slug: k3s-master
description: Allows to run a k3s master as an Home Assistant addon
url: "https://github.com/koenigsreiter/homeassistant_addons/tree/main/k3s-master"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/koenigsreiter/homeassistant_addons/{arch}-addon-k3s-master"
